In [35]:
name = "Ramata"
age = 25
print(f"{name} is {age} old.")

Ramata is 25 old.


In [36]:
print("{} is {} old".format(name,age))

Ramata is 25 old


In [37]:
x ="Fuck you.\tYour motherfuck."
print(x)

Fuck you.	Your motherfuck.


In [38]:
print(r" Michael Jackson \ is the best" )

 Michael Jackson \ is the best


In [39]:
print(r'Il love you.\nAnd all')

Il love you.\nAnd all


In [40]:
"helloMike".find("Mike")

5

In [41]:
list1 =[1,2,3,'boss']

In [42]:
list1.extend([3,5])
list1

[1, 2, 3, 'boss', 3, 5]

In [43]:
tuple1 = (1,2,3,4,5)

In [44]:
tuple1

(1, 2, 3, 4, 5)

In [45]:
tuple1.extend([2,3])

AttributeError: 'tuple' object has no attribute 'extend'

In [ ]:
list1

[1, 2, 3, 'boss', 3, 5]

In [ ]:
list1[0] = 10

In [ ]:
list1

[10, 2, 3, 'boss', 3, 5]

In [ ]:
tuple1[0] = 14

TypeError: 'tuple' object does not support item assignment

In [ ]:
del(list1[0])

In [ ]:
list1

[2, 3, 'boss', 3, 5]

In [ ]:
my_list = [1, 2, 3, 4, 5] 
my_list.insert(2, 6) 
print(my_list)

[1, 2, 6, 3, 4, 5]


In [ ]:
my_list.pop(2)

6

In [ ]:
my_list

[1, 2, 3, 4, 5]

In [ ]:
[1,2,3] + [1,1,1]

[1, 2, 3, 1, 1, 1]

In [ ]:
A = [1]
A.append([2,3,4,5])
A

[1, [2, 3, 4, 5]]

In [ ]:
i = 18
if i >= 18:
    print("Majeur")
elif i >= 15:
    print("Adolescent")
else:
    print("Enfant")

Majeur


In [ ]:
i = 0
while i < 10 :
    print("Je dois lever la main.")
    i=i+1

Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.


In [ ]:
v = 'je crois en Dieu.'
for i in v:
    print(i)

j
e
 
c
r
o
i
s
 
e
n
 
D
i
e
u
.


In [ ]:
liste = [1,5,10,15,20,25]
for i in liste:
    if i > 15:
        print("On stoppe la boucle")
        break
    print(i)

1
5
10
15
On stoppe la boucle


In [ ]:
for i in range(0,11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
squares = ['red', 'yellow', 'green', 'purple', 'blue']

for i in range(0, 5):
    print("Before square ", i, 'is',  squares[i])
    squares[i] = 'white'
    print("After square ", i, 'is',  squares[i])

Before square  0 is red
After square  0 is white
Before square  1 is yellow
After square  1 is white
Before square  2 is green
After square  2 is white
Before square  3 is purple
After square  3 is white
Before square  4 is blue
After square  4 is white


In [ ]:
def plus(a):
    b=a+1
    return b
plus(5)

6

In [ ]:
len([sum([1,1,1])])

1

In [ ]:
L=[1,3,2]

sorted(L)b

[1, 2, 3]

In [ ]:
class Circle(object):
    # Constructor
    def __init__(self, radius=3, color='blue'):
        self.radius = radius
        self.color = color


    # Method
    def add_radius(self, r):
        self.radius = self.radius + r
        return self.radius

In [ ]:
x = 'GO'
if x == 'GO':
    print('GO')
else:
    print('Stop')
print('Mike')

GO
Mike


In [ ]:
x = 1
x = x > 5
x

False

In [ ]:
x=0
while x<2:
    print(x)
    x = x+1

0
1


In [ ]:
class Points(object): 
    def __init__(self, x, y): 
        self.x = x 
        self.y = y 
    def print_point(self): 
        print('x=', self.x, ' y=', self.y) 


p1 = Points(1, 2) 
p1.print_point()

x= 1  y= 2


In [ ]:
with open("/Users/delidji/Documents/Data-Analyst-Project/0. Learning/basics 0/mytext.txt","r") as file_1:
    for i in file_1:
        print(i)

Comment vas-tu

Je me porte bien.

Et toi





In [ ]:
file = open("/Users/delidji/Documents/Data-Analyst-Project/0. Learning/basics 0/mytext.txt","r")
print(file.readlines())

['Comment vas-tu\n', 'Je me porte bien.\n', 'Et toi\n', '\n']


In [ ]:
import pandas as pd

In [ ]:
with open("/Users/delidji/Documents/Data-Analyst-Project/0. Learning/basics 0/example.txt","w") as file_2:
    file_2.write("Yes, I did it\n")
    file_2.write('Fuck you\n')
    file_2.write("Go ! Go ! Brandon\n")

In [ ]:
with open("/Users/delidji/Documents/Data-Analyst-Project/0. Learning/basics 0/example.txt","r") as file_3:
    i=0
    for i in file_3:
        print(i)

Yes, I did it

Fuck you

Go ! Go ! Brandon



In [46]:
age = [23,45,56,54]
serie = pd.Series(age)
serie

0    23
1    45
2    56
3    54
dtype: int64

In [49]:
data = {"name" : ["Hinata","Francesca","Paola","Fatou"],
        "age":[25,33,21,34],
        "country" : ["Japan", "Brazil", "Spain","Senegal"]}
raw= pd.DataFrame(data)
raw

name  age  country
0     Hinata   25    Japan
1  Francesca   33   Brazil
2      Paola   21    Spain
3      Fatou   34  Senegal

In [51]:
df_upper30 = raw[raw["age"] > 30]
df_upper30

name  age  country
1  Francesca   33   Brazil
3      Fatou   34  Senegal

In [52]:
import numpy as np
a = [0,1,2,3,4,5]
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5])

In [53]:
b.size

6

In [54]:
b.ndim

1

In [55]:
b.shape

(6,)

In [56]:
b[0] = 200
b

array([200,   1,   2,   3,   4,   5])

In [57]:
b[0:3]

array([200,   1,   2])

In [58]:
b * 2

array([400,   2,   4,   6,   8,  10])

In [59]:
a * b

array([ 0,  1,  4,  9, 16, 25])

In [60]:
e = np.linspace(-1,1,5)
e

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [62]:
a = np.array([0,1])
b = np.array([1,0])
c = np.dot(a,b)
c

0

In [65]:
X = np.array([[1,0,1],[2,2,2]])
out = X[0:2,2]
out

array([1, 2])

# WEB SCRAPPING

In [127]:
import pandas as pd
import numpy as np 

In [128]:
url = "https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"
tables = pd.read_html(url)

In [129]:
df = tables[3]
df

Country/Territory UN region IMF[1][13]            World Bank[14]  \
    Country/Territory UN region   Estimate       Year       Estimate   
0               World         —  105568776       2023      100562011   
1       United States  Americas   26854599       2023       25462700   
2               China      Asia   19373586  [n 1]2023       17963171   
3               Japan      Asia    4409738       2023        4231141   
4             Germany    Europe    4308854       2023        4072192   
..                ...       ...        ...        ...            ...   
209          Anguilla  Americas          —          —              —   
210          Kiribati   Oceania        248       2023            223   
211             Nauru   Oceania        151       2023            151   
212        Montserrat  Americas          —          —              —   
213            Tuvalu   Oceania         65       2023             60   

               United Nations[15]             
          Year           Estimate       Year  
0         2022           96698005       2021  
1         2022           23315081       2021  
2    [n 3]2022           17734131  [n 1]2021  
3         2022            4940878       2021  
4         2022            4259935       2021  
..         ...                ...        ...  
209          —                303       2021  
210       2022                227       2021  
211       2022                155       2021  
212          —                 72       2021  
213       2022                 60       2021  

[214 rows x 8 columns]

In [130]:
df.columns

MultiIndex([( 'Country/Territory', 'Country/Territory'),
            (         'UN region',         'UN region'),
            (        'IMF[1][13]',          'Estimate'),
            (        'IMF[1][13]',              'Year'),
            (    'World Bank[14]',          'Estimate'),
            (    'World Bank[14]',              'Year'),
            ('United Nations[15]',          'Estimate'),
            ('United Nations[15]',              'Year')],
           )

In [131]:
df.shape

(214, 8)

In [132]:
df.columns = range(df.shape[1])
df

0         1          2          3          4          5  \
0            World         —  105568776       2023  100562011       2022   
1    United States  Americas   26854599       2023   25462700       2022   
2            China      Asia   19373586  [n 1]2023   17963171  [n 3]2022   
3            Japan      Asia    4409738       2023    4231141       2022   
4          Germany    Europe    4308854       2023    4072192       2022   
..             ...       ...        ...        ...        ...        ...   
209       Anguilla  Americas          —          —          —          —   
210       Kiribati   Oceania        248       2023        223       2022   
211          Nauru   Oceania        151       2023        151       2022   
212     Montserrat  Americas          —          —          —          —   
213         Tuvalu   Oceania         65       2023         60       2022   

            6          7  
0    96698005       2021  
1    23315081       2021  
2    17734131  [n 1]2021  
3     4940878       2021  
4     4259935       2021  
..        ...        ...  
209       303       2021  
210       227       2021  
211       155       2021  
212        72       2021  
213        60       2021  

[214 rows x 8 columns]

In [133]:
df = df[[0,2]]
df

0          2
0            World  105568776
1    United States   26854599
2            China   19373586
3            Japan    4409738
4          Germany    4308854
..             ...        ...
209       Anguilla          —
210       Kiribati        248
211          Nauru        151
212     Montserrat          —
213         Tuvalu         65

[214 rows x 2 columns]

In [134]:
df = df.iloc[1:11,:]
df

0         2
1    United States  26854599
2            China  19373586
3            Japan   4409738
4          Germany   4308854
5            India   3736882
6   United Kingdom   3158938
7           France   2923489
8            Italy   2169745
9           Canada   2089672
10          Brazil   2081235

In [135]:
df.columns = ["Country","GDP (Million USD)"]

In [136]:
df

Country GDP (Million USD)
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

In [137]:
df["GDP (Million USD)"] = df["GDP (Million USD)"].astype(int)

/var/folders/zt/s0q0y4yd4qj22t8gpmfncqtm0000gn/T/ipykernel_2143/1395936141.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GDP (Million USD)"] = df["GDP (Million USD)"].astype(int)


In [138]:
df[['GDP (Million USD)']] = df[['GDP (Million USD)']]/1000
df

/var/folders/zt/s0q0y4yd4qj22t8gpmfncqtm0000gn/T/ipykernel_2143/784426526.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['GDP (Million USD)']] = df[['GDP (Million USD)']]/1000


Country  GDP (Million USD)
1    United States          26854.599
2            China          19373.586
3            Japan           4409.738
4          Germany           4308.854
5            India           3736.882
6   United Kingdom           3158.938
7           France           2923.489
8            Italy           2169.745
9           Canada           2089.672
10          Brazil           2081.235

In [139]:
df[['GDP (Million USD)']] = np.round(df[['GDP (Million USD)']], 2)
df

/var/folders/zt/s0q0y4yd4qj22t8gpmfncqtm0000gn/T/ipykernel_2143/3900435537.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['GDP (Million USD)']] = np.round(df[['GDP (Million USD)']], 2)


Country  GDP (Million USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [140]:
df.rename(columns = {'GDP (Million USD)' : 'GDP (Billion USD)'})
df

Country  GDP (Million USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [123]:
url2 = "https://en.wikipedia.org/wiki/World_population"
df2 = pd.read_html(url2)
df2

[      Population         1     2     3     4     5     6     7     8     9  \
 0           Year      1804  1927  1960  1974  1987  1999  2011  2022  2037   
 1  Years elapsed  200,000+   123    33    14    13    12    12    11    15   
 
      10  
 0  2057  
 1    20  ,
                                Region  2022 (percent)  2030 (percent)  \
 0                  Sub-Saharan Africa  1,152 (14.51%)  1,401 (16.46%)   
 1    Northern Africa and Western Asia     549 (6.91%)     617 (7.25%)   
 2      Central Asia and Southern Asia  2,075 (26.13%)  2,248 (26.41%)   
 3  Eastern Asia and Southeastern Asia  2,342 (29.49%)  2,372 (27.87%)   
 4         Europe and Northern America  1,120 (14.10%)  1,129 (13.26%)   
 5     Latin America and the Caribbean     658 (8.29%)     695 (8.17%)   
 6           Australia and New Zealand      31 (0.39%)      34 (0.40%)   
 7                             Oceania      14 (0.18%)      15 (0.18%)   
 8                               World            7942       

In [124]:
table = df2[8]
table

Rank         Country  Population  Area (km2)  Density (pop/km2)  \
0     1           India  1389637446     3287263                423   
1     2        Pakistan   242923845      796095                305   
2     3      Bangladesh   165650475      148460               1116   
3     4           Japan   124214766      377915                329   
4     5     Philippines   114597229      300000                382   
5     6         Vietnam   103808319      331210                313   
6     7  United Kingdom    67791400      243610                278   
7     8     South Korea    51844834       99720                520   
8     9          Taiwan    23580712       35980                655   
9    10       Sri Lanka    23187516       65610                353   

  Population trend[citation needed]  
0                           Growing  
1                   Rapidly growing  
2                           Growing  
3                    Declining[104]  
4                           Growing  
5                           Growing  
6                           Growing  
7                            Steady  
8                            Steady  
9                           Growing

In [125]:
table = table[["Country","Population"]]
table

Country  Population
0           India  1389637446
1        Pakistan   242923845
2      Bangladesh   165650475
3           Japan   124214766
4     Philippines   114597229
5         Vietnam   103808319
6  United Kingdom    67791400
7     South Korea    51844834
8          Taiwan    23580712
9       Sri Lanka    23187516