In [35]:
name = "Ramata"
age = 25
print(f"{name} is {age} old.")

Ramata is 25 old.


In [36]:
print("{} is {} old".format(name,age))

Ramata is 25 old


In [37]:
x ="Fuck you.\tYour motherfuck."
print(x)

Fuck you.	Your motherfuck.


In [38]:
print(r" Michael Jackson \ is the best" )

 Michael Jackson \ is the best


In [39]:
print(r'Il love you.\nAnd all')

Il love you.\nAnd all


In [40]:
"helloMike".find("Mike")

5

In [41]:
list1 =[1,2,3,'boss']

In [42]:
list1.extend([3,5])
list1

[1, 2, 3, 'boss', 3, 5]

In [43]:
tuple1 = (1,2,3,4,5)

In [44]:
tuple1

(1, 2, 3, 4, 5)

In [45]:
tuple1.extend([2,3])

AttributeError: 'tuple' object has no attribute 'extend'

In [ ]:
list1

[1, 2, 3, 'boss', 3, 5]

In [ ]:
list1[0] = 10

In [ ]:
list1

[10, 2, 3, 'boss', 3, 5]

In [ ]:
tuple1[0] = 14

TypeError: 'tuple' object does not support item assignment

In [ ]:
del(list1[0])

In [ ]:
list1

[2, 3, 'boss', 3, 5]

In [ ]:
my_list = [1, 2, 3, 4, 5] 
my_list.insert(2, 6) 
print(my_list)

[1, 2, 6, 3, 4, 5]


In [ ]:
my_list.pop(2)

6

In [ ]:
my_list

[1, 2, 3, 4, 5]

In [ ]:
[1,2,3] + [1,1,1]

[1, 2, 3, 1, 1, 1]

In [ ]:
A = [1]
A.append([2,3,4,5])
A

[1, [2, 3, 4, 5]]

In [ ]:
i = 18
if i >= 18:
    print("Majeur")
elif i >= 15:
    print("Adolescent")
else:
    print("Enfant")

Majeur


In [ ]:
i = 0
while i < 10 :
    print("Je dois lever la main.")
    i=i+1

Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.
Je dois lever la main.


In [ ]:
v = 'je crois en Dieu.'
for i in v:
    print(i)

j
e
 
c
r
o
i
s
 
e
n
 
D
i
e
u
.


In [ ]:
liste = [1,5,10,15,20,25]
for i in liste:
    if i > 15:
        print("On stoppe la boucle")
        break
    print(i)

1
5
10
15
On stoppe la boucle


In [ ]:
for i in range(0,11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
squares = ['red', 'yellow', 'green', 'purple', 'blue']

for i in range(0, 5):
    print("Before square ", i, 'is',  squares[i])
    squares[i] = 'white'
    print("After square ", i, 'is',  squares[i])

Before square  0 is red
After square  0 is white
Before square  1 is yellow
After square  1 is white
Before square  2 is green
After square  2 is white
Before square  3 is purple
After square  3 is white
Before square  4 is blue
After square  4 is white


In [ ]:
def plus(a):
    b=a+1
    return b
plus(5)

6

In [ ]:
len([sum([1,1,1])])

1

In [ ]:
L=[1,3,2]

sorted(L)b

[1, 2, 3]

In [ ]:
class Circle(object):
    # Constructor
    def __init__(self, radius=3, color='blue'):
        self.radius = radius
        self.color = color


    # Method
    def add_radius(self, r):
        self.radius = self.radius + r
        return self.radius

In [ ]:
x = 'GO'
if x == 'GO':
    print('GO')
else:
    print('Stop')
print('Mike')

GO
Mike


In [ ]:
x = 1
x = x > 5
x

False

In [ ]:
x=0
while x<2:
    print(x)
    x = x+1

0
1


In [ ]:
class Points(object): 
    def __init__(self, x, y): 
        self.x = x 
        self.y = y 
    def print_point(self): 
        print('x=', self.x, ' y=', self.y) 


p1 = Points(1, 2) 
p1.print_point()

x= 1  y= 2


In [ ]:
with open("/Users/delidji/Documents/Data-Analyst-Project/0. Learning/basics 0/mytext.txt","r") as file_1:
    for i in file_1:
        print(i)

Comment vas-tu

Je me porte bien.

Et toi





In [ ]:
file = open("/Users/delidji/Documents/Data-Analyst-Project/0. Learning/basics 0/mytext.txt","r")
print(file.readlines())

['Comment vas-tu\n', 'Je me porte bien.\n', 'Et toi\n', '\n']


In [ ]:
import pandas as pd

In [ ]:
with open("/Users/delidji/Documents/Data-Analyst-Project/0. Learning/basics 0/example.txt","w") as file_2:
    file_2.write("Yes, I did it\n")
    file_2.write('Fuck you\n')
    file_2.write("Go ! Go ! Brandon\n")

In [ ]:
with open("/Users/delidji/Documents/Data-Analyst-Project/0. Learning/basics 0/example.txt","r") as file_3:
    i=0
    for i in file_3:
        print(i)

Yes, I did it

Fuck you

Go ! Go ! Brandon



In [46]:
age = [23,45,56,54]
serie = pd.Series(age)
serie

0    23
1    45
2    56
3    54
dtype: int64

In [49]:
data = {"name" : ["Hinata","Francesca","Paola","Fatou"],
        "age":[25,33,21,34],
        "country" : ["Japan", "Brazil", "Spain","Senegal"]}
raw= pd.DataFrame(data)
raw

name  age  country
0     Hinata   25    Japan
1  Francesca   33   Brazil
2      Paola   21    Spain
3      Fatou   34  Senegal

In [51]:
df_upper30 = raw[raw["age"] > 30]
df_upper30

name  age  country
1  Francesca   33   Brazil
3      Fatou   34  Senegal

In [52]:
import numpy as np
a = [0,1,2,3,4,5]
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5])

In [53]:
b.size

6

In [54]:
b.ndim

1

In [55]:
b.shape

(6,)

In [56]:
b[0] = 200
b

array([200,   1,   2,   3,   4,   5])

In [57]:
b[0:3]

array([200,   1,   2])

In [58]:
b * 2

array([400,   2,   4,   6,   8,  10])

In [59]:
a * b

array([ 0,  1,  4,  9, 16, 25])

In [60]:
e = np.linspace(-1,1,5)
e

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [62]:
a = np.array([0,1])
b = np.array([1,0])
c = np.dot(a,b)
c

0

In [65]:
X = np.array([[1,0,1],[2,2,2]])
out = X[0:2,2]
out

array([1, 2])